name: continious integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@master
      - name: build & test with maven
        run: mvn -B install
      - name: prepare release of maven package
        if: github.ref == 'refs/heads/master'
        uses: navikt/bidrag-actions/release-prepare-mvn-pkg@master
        with:
          new_snapshot_version_file_name: .new-snapshot-version
          release_version_file_name: .release-version
      - name: is artifact eligable for deployment
        if: github.ref == 'refs/heads/master'
        uses: navikt/bidrag-actions/release-verify-auto-deploy@master
        with:
          changelog_file: README.md
          release_version_file: .release-version
      - name: release maven package
        if: github.ref == 'refs/heads/master'
        uses: navikt/bidrag-actions/release-mvn-pkg@master
        with:
          new_snapshot_version_file: .new-snapshot-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: commit new version
        if: github.ref == 'refs/heads/master'
        uses: Endbug/add-and-commit@v2.3.0
        with:
          message: "Bumped to new SNAPSHOT version after release by ${{ github.actor }}."
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
