name: continious integration
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: env
      - uses: navikt/bidrag-actions/verify-mvn-dependencies@v1.0.1
      - run: mvn -B install -e
      - uses: navikt/bidrag-actions/release-prepare-mvn-pkg@v1.0.1
        if: github.ref == 'refs/heads/master'
        with:
          new_snapshot_version_file_name: .new-snapshot-version
          release_version_file_name: .release-version
      - uses: navikt/bidrag-actions/release-verify-auto-deploy@v1.0.0
        if: github.ref == 'refs/heads/master'
        with:
          changelog_file: README.md
          release_version_file: .release-version
      - uses: navikt/bidrag-actions/release-mvn-pkg@v4.0.5
        if: github.ref == 'refs/heads/master'
        with:
          new_snapshot_version_file: .new-snapshot-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-actions/git-tag-n-commit-mvn-deploy@v4.0.0
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version {}
          tag_message: Release new version {}
          pattern: pom.xml
          tag_file: .release-version
          is_release_file: .is-release-candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
